
- name: Start And Enable Etcd Service
  systemd:
    name: etcd
    state: started
    enabled: true
    daemon_reload: true
  register: etcd_status

- name: Wait Etcd Service Started
  ansible.builtin.wait_for:
    port: 2379
    state: started
    timeout: 60

- name: Check Etcd Cluster Healthly 
  shell: |
    ln -sfT {{ etcd_home }}/bin/etcdctl /usr/local/bin/etcdctl
    export ENDPOINT='--endpoints={% for host in groups['etcd'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}:2379{% if not loop.last %},{% endif %}{% endfor %}'
    export ETCD_ARGS='--cacert={{ etcd_home }}/ssl/ca.pem --cert={{ etcd_home }}/ssl/etcd.pem --key={{ etcd_home }}/ssl/etcd-key.pem --write-out=table'
    etcdctl $ETCD_ARGS member list
    etcdctl $ETCD_ARGS endpoint status
    etcdctl $ETCD_ARGS endpoint health
    etcdctl $ENDPOINT $ETCD_ARGS endpoint status
  when: inventory_hostname == groups['etcd'][0]
  register: shell_output

- name: Print Etcd Cluster Status
  ansible.builtin.debug:
    msg: "{{ shell_output.stdout_lines }}"
  when: inventory_hostname == groups['etcd'][0]