
- name: Copy Ingress-Nginx Images To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/images/ingress-nginx"
    dest: "/tmp/"
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"

- name: Load Ingress-Nginx Images
  ansible.builtin.shell: |
    ls /tmp/ingress-nginx/*.tar|xargs -n 1 ctr -n k8s.io i import
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"
  async: 3600
  poll: 0

- name: Copy Ingress-Nginx Manifest To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/ingress-nginx-{{ ingress_nginx_version }}.yaml"
    dest: "/tmp/ingress-nginx-{{ ingress_nginx_version }}.yaml"

- name: Install Ingress-Nginx Use Manifest
  ansible.builtin.shell: |
    sed -i -E  's#@sha256:[a-f0-9]+##g' /tmp/ingress-nginx-{{ ingress_nginx_version }}.yaml
    sed -i "s#registry.k8s.io#{{ ingress_registry_prefix }}/registry.k8s.io#g" /tmp/ingress-nginx-{{ ingress_nginx_version }}.yaml
    kubectl apply -f /tmp/ingress-nginx-{{ ingress_nginx_version }}.yaml
    kubectl patch ingressclass nginx -p '{"metadata":{"annotations":{"ingressclass.kubernetes.io/is-default-class":"true"}}}'
