
# - name: Downloading Ingress-Nginx Helm Chart
#   amazon.aws.s3_object:
#     endpoint_url: "{{ s3_endpoint_url }}"
#     access_key: "{{ s3_access_key }}"
#     secret_key: "{{ s3_secret_key }}"
#     bucket: "{{ s3_bucket_name }}"
#     object: "ingress-nginx/ingress-nginx-{{ ingress_helm_version }}.tgz"
#     dest: "{{ playbook_dir }}/.ansible_temp/ingress-nginx-{{ ingress_helm_version }}.tgz"
#     mode: get
#     overwrite: different
#   delegate_to: localhost
#   run_once: true

# - name: Copy Ingress-Nginx Helm Chart To Remote Host
#   ansible.builtin.copy:
#     src: "{{ playbook_dir }}/.ansible_temp/ingress-nginx-{{ ingress_helm_version }}.tgz"
#     dest: "/tmp/ingress-nginx-{{ ingress_helm_version }}.tgz"

# - name: Wait Cluster Network Ready
#   ansible.builtin.wait_for:
#     host: "{{ kube_cluster_apiserver }}"
#     port: 443
#     state: started
#     timeout: 600

# - name: Install Ingress-Nginx
#   kubernetes.core.helm:
#     chart_ref: "/tmp/ingress-nginx-{{ ingress_helm_version }}.tgz"
#     name: ingress-nginx
#     chart_version: "{{ ingress_helm_version }}"
#     wait: false
#     # state: absent
#     release_namespace: ingress-nginx
#     create_namespace: true
#     values:
#       global:
#         image:
#           registry: "{{ ingress_registry_prefix }}/registry.k8s.io"
#       controller:
#         tag: "{{ ingress_nginx_version }}"
#         service:
#           nodePorts:
#             http: "{{ ingress_nodeport_http }}"
#             https: "{{ ingress_nodeport_https }}"
#         ingressClassResource:
#           default: true
        
# - name: Downloading Ingress-Nginx Manifest
#   amazon.aws.s3_object:
#     endpoint_url: "{{ s3_endpoint_url }}"
#     access_key: "{{ s3_access_key }}"
#     secret_key: "{{ s3_secret_key }}"
#     bucket: "{{ s3_bucket_name }}"
#     object: "ingress-nginx/{{ ingress_nginx_version }}/deploy.yaml"
#     dest: "{{ playbook_dir }}/.ansible_temp/ingress-nginx.yaml"
#     mode: get
#     overwrite: different
#   delegate_to: localhost
#   run_once: true

- name: Copy Ingress-Nginx Images To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/images/ingress-nginx"
    dest: "/tmp/"
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"

- name: Load Ingress-Nginx Images
  ansible.builtin.shell: |
    ls /tmp/ingress-nginx/*.tar|xargs -n 1 ctr -n k8s.io i import
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"
  async: 3600
  poll: 0

- name: Copy Ingress-Nginx Manifest To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/ingress-nginx.yaml"
    dest: "/tmp/ingress-nginx.yaml"

- name: Install Ingress-Nginx Use Manifest
  ansible.builtin.shell: |
    kubectl apply -f /tmp/ingress-nginx.yaml
    kubectl patch ingressclass nginx -p '{"metadata":{"annotations":{"ingressclass.kubernetes.io/is-default-class":"true"}}}'
