
- name: Copy k8spilot Artifact To Remote Host
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ playbook_dir }}/artifacts/images/k8spilot", dest:  "/tmp/" }
    - { src: "pilot-job.yaml", dest: "{{ kubernetes_home}}/etc/pilot-job.yaml" }

- name: Load k8spilot Images
  ansible.builtin.shell: ls /tmp/k8spilot/*.tar|xargs -n 1 ctr -n k8s.io i import
  async: 3600
  poll: 0

- name: Deploy k8spilot Job
  ansible.builtin.shell: kubectl apply -f "{{ kubernetes_home}}/etc/pilot-job.yaml"

- name: Copy tigera-operator Helm Chart To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/tigera-operator-{{ calico_version }}.tgz"
    dest: "/tmp/tigera-operator-{{ calico_version }}.tgz"

- name: Copy tigera-operator Values Override File
  ansible.builtin.template:
    src: "tigera-operator-values-override.yaml.j2"
    dest: "/tmp/tigera-operator-values-override.yaml"
    mode: '0644'

- name: Copy Calico Offline Images To Remote Host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/artifacts/images/calico"
    dest: "/tmp/"
    mode: '0644'
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"

- name: Load Calico Images
  ansible.builtin.shell: |
    ls /tmp/calico/*.tar|xargs -n 1 ctr -n k8s.io i import
  delegate_to: "{{ item }}"
  loop: "{{ groups['worker'] }}"
  async: 3600
  poll: 0 

- name: Install tigera-operator
  ansible.builtin.shell: |
    helm upgrade --install tigera-operator /tmp/tigera-operator-{{ calico_version }}.tgz --namespace tigera-operator --create-namespace --values /tmp/tigera-operator-values-override.yaml
