
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8spilot
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8spilot
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8spilot
subjects:
- kind: ServiceAccount
  name: k8spilot
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8spilot
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  name: pilot-job
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      hostNetwork: true 
      serviceAccountName: k8spilot
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.k8spilot.io/network-not-ready"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: pilot-job
        image: quay.io/k8spilot/pilot-job:v1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "127.0.0.1"
        - name: KUBERNETES_SERVICE_PORT
          value: "6443"
      restartPolicy: Never