name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Quay.io
      run: echo "${{ secrets.PASSWORD }}" | docker login quay.io -u "${{ secrets.USERNAME }}" --password-stdin
    - name: Build image and push (multi-platform)
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64
        tags: quay.io/k8spilot/k8spilot:${{ github.ref_name }}
        push: true
